---
- name: Deploy YOLO E-commerce App with Docker using Ansible
  hosts: all
  become: true
  tasks:
    - name: Clone e-commerce repository from GitHub
      git:
        repo: 'https://github.com/Mattmbugua/yolo.git'
        dest: '/home/vagrant/app'
    
  roles:
    - { role: docker-setup,      tags: ["docker-setup"] }
    - { role: network_setup,      tags: ["network"] }
    - { role: setup-mongodb,      tags: ["mongodb"] }
    - { role: backend-deployment, tags: ["backend"] }
    - { role: frontend-deployment, tags: ["frontend"] }
    
    
    