
- name: Create Docker volume
  docker_volume:
    name: app-mongo-data

- name: Create app-net Docker network
  docker_network:
    name: app-net
    driver: bridge

- name: Pull MongoDB image
  docker_image:
    name: mongo
    source: pull

- name: Create MongoDB container
  docker_container:
    name: app-mongo
    image: mongo
    state: started
    ports:
      - "27017:27017"
    volumes:
      - app-mongo-data:/data/db
    networks:
      - name: app-net
