apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: bigmatt98/ecommerce-backend:1.0.1
        ports:
        - containerPort: 5000 
        env:
        - name: MONGO_URL
          value: mongodb://mongo-0.mongo.default.svc.cluster.local:27017/ecommerce
