apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # exposed to the outside world
      targetPort: 80  # matches Nginx container port inside the pod
