- name: Pull backend image
  docker_image:
    name: bigmatt98/ecommerce-backend:1.0.1
    source: pull

- name: Create backend container
  docker_container:
    name: matt-backend-container
    image: bigmatt98/ecommerce-backend:1.0.1
    ports:
      - "5000:5000"
    env:
      MONGO_URI: "mongodb://app-mongo:27017/yolomy"
    networks:
      - name: app-net
    restart_policy: always
   
